import { randomUUID, createHash } from 'node:crypto';
import { query } from './db.js';
import { assert } from './errors.js';
import { audit } from './audit.js';
import { hasPermission, requirePermission } from './auth.js';
import { getMemberDetail } from './backoffice.js';

const clean=(v,max=500)=>String(v??'').trim().slice(0,max);
const nullable=(v,max=500)=>clean(v,max)||null;
const num=(v)=>v===null||v===undefined||v===''?null:Number(v);
const bounded=(v,min,max,name)=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);assert(Number.isSafeInteger(n)&&n>=min&&n<=max,400,`${name} tidak valid.`,`${name.toUpperCase().replace(/\W+/g,'_')}_INVALID`);return n;};
const severityFor=score=>score>=90?'CRITICAL':score>=70?'HIGH':score>=40?'MEDIUM':'LOW';
const hash=v=>createHash('sha256').update(String(v)).digest('hex');

async function ensureCompliance(memberId){await query(`INSERT INTO member_compliance_profiles(member_id) VALUES($1) ON CONFLICT(member_id) DO NOTHING`,[memberId]);return (await query(`SELECT * FROM member_compliance_profiles WHERE member_id=$1`,[memberId])).rows[0];}
async function ensureResponsible(memberId){await query(`INSERT INTO responsible_play_profiles(member_id) VALUES($1) ON CONFLICT(member_id) DO NOTHING`,[memberId]);return applyPendingResponsible(memberId);}
async function applyPendingResponsible(memberId){
  const row=(await query(`SELECT * FROM responsible_play_profiles WHERE member_id=$1`,[memberId])).rows[0];if(!row)return null;
  if(row.pending_limits&&row.pending_effective_at&&new Date(row.pending_effective_at)<=new Date()){
    const p=row.pending_limits||{};await query(`UPDATE responsible_play_profiles SET deposit_daily_limit=COALESCE($1,deposit_daily_limit),deposit_weekly_limit=COALESCE($2,deposit_weekly_limit),deposit_monthly_limit=COALESCE($3,deposit_monthly_limit),spend_daily_limit=COALESCE($4,spend_daily_limit),session_minutes_limit=COALESCE($5,session_minutes_limit),pending_limits=NULL,pending_effective_at=NULL,updated_at=now() WHERE member_id=$6`,[p.depositDailyLimit??null,p.depositWeeklyLimit??null,p.depositMonthlyLimit??null,p.spendDailyLimit??null,p.sessionMinutesLimit??null,memberId]);
    return (await query(`SELECT * FROM responsible_play_profiles WHERE member_id=$1`,[memberId])).rows[0];
  }
  return row;
}
const mapResponsible=r=>r?({memberId:r.member_id,depositDailyLimit:r.deposit_daily_limit===null?null:Number(r.deposit_daily_limit),depositWeeklyLimit:r.deposit_weekly_limit===null?null:Number(r.deposit_weekly_limit),depositMonthlyLimit:r.deposit_monthly_limit===null?null:Number(r.deposit_monthly_limit),spendDailyLimit:r.spend_daily_limit===null?null:Number(r.spend_daily_limit),sessionMinutesLimit:r.session_minutes_limit===null?null:Number(r.session_minutes_limit),coolingOffUntil:r.cooling_off_until,selfExcludedUntil:r.self_excluded_until,pendingLimits:r.pending_limits||null,pendingEffectiveAt:r.pending_effective_at,source:r.source,updatedAt:r.updated_at}):null;
const mapCompliance=r=>r?({memberId:r.member_id,kycStatus:r.kyc_status,riskScore:r.risk_score,riskLevel:r.risk_level,countryCode:r.country_code,dateOfBirth:r.date_of_birth,verificationProvider:r.verification_provider,verificationReference:r.verification_reference,verifiedAt:r.verified_at,lastReviewedAt:r.last_reviewed_at,notes:r.notes,updatedAt:r.updated_at}):null;

export async function getResponsiblePlay(memberId){return mapResponsible(await ensureResponsible(memberId));}

export async function updateMemberResponsiblePlay(session,input,ip=''){
  const current=await ensureResponsible(session.userId);
  const incoming={
    depositDailyLimit:bounded(input.depositDailyLimit,10000,200000000,'deposit daily limit'),
    depositWeeklyLimit:bounded(input.depositWeeklyLimit,10000,1000000000,'deposit weekly limit'),
    depositMonthlyLimit:bounded(input.depositMonthlyLimit,10000,4000000000,'deposit monthly limit'),
    spendDailyLimit:bounded(input.spendDailyLimit,1000,200000000,'spend daily limit'),
    sessionMinutesLimit:bounded(input.sessionMinutesLimit,15,1440,'session minutes limit')
  };
  const columns=[['depositDailyLimit','deposit_daily_limit'],['depositWeeklyLimit','deposit_weekly_limit'],['depositMonthlyLimit','deposit_monthly_limit'],['spendDailyLimit','spend_daily_limit'],['sessionMinutesLimit','session_minutes_limit']];
  const immediate={},pending={};
  for(const [key,col] of columns){const next=incoming[key];if(next===null)continue;const old=current[col]===null?null:Number(current[col]);if(old===null||next<=old)immediate[key]=next;else pending[key]=next;}
  const cooling=input.coolingOffUntil?new Date(input.coolingOffUntil):null;const self=input.selfExcludedUntil?new Date(input.selfExcludedUntil):null;const now=Date.now();
  if(cooling)assert(Number.isFinite(cooling.getTime())&&cooling.getTime()>now,400,'Cooling-off harus di masa depan.','COOLING_OFF_INVALID');
  if(self)assert(Number.isFinite(self.getTime())&&self.getTime()>=now+24*3600*1000,400,'Self-exclusion minimal 24 jam.','SELF_EXCLUSION_INVALID');
  await query(`UPDATE responsible_play_profiles SET deposit_daily_limit=COALESCE($1,deposit_daily_limit),deposit_weekly_limit=COALESCE($2,deposit_weekly_limit),deposit_monthly_limit=COALESCE($3,deposit_monthly_limit),spend_daily_limit=COALESCE($4,spend_daily_limit),session_minutes_limit=COALESCE($5,session_minutes_limit),cooling_off_until=COALESCE($6,cooling_off_until),self_excluded_until=COALESCE($7,self_excluded_until),pending_limits=$8::jsonb,pending_effective_at=$9,source='MEMBER',updated_by=$10,updated_at=now() WHERE member_id=$10`,[immediate.depositDailyLimit??null,immediate.depositWeeklyLimit??null,immediate.depositMonthlyLimit??null,immediate.spendDailyLimit??null,immediate.sessionMinutesLimit??null,cooling,self,Object.keys(pending).length?JSON.stringify(pending):null,Object.keys(pending).length?new Date(Date.now()+24*3600*1000):null,session.userId]);
  await audit({actorId:session.userId,actorRole:'MEMBER',action:'RESPONSIBLE_PLAY_UPDATED',targetType:'USER',targetId:session.userId,details:{immediate,pending,coolingOffUntil:cooling,selfExcludedUntil:self},ip});
  return getResponsiblePlay(session.userId);
}

export async function adminUpdateResponsiblePlay(session,memberId,input,ip=''){
  requirePermission(session,'responsible:write');await ensureResponsible(memberId);
  const d=bounded(input.depositDailyLimit,0,200000000,'deposit daily limit'),w=bounded(input.depositWeeklyLimit,0,1000000000,'deposit weekly limit'),m=bounded(input.depositMonthlyLimit,0,4000000000,'deposit monthly limit'),s=bounded(input.spendDailyLimit,0,200000000,'spend daily limit'),mins=bounded(input.sessionMinutesLimit,15,1440,'session minutes limit');
  const cooling=input.coolingOffUntil?new Date(input.coolingOffUntil):null,self=input.selfExcludedUntil?new Date(input.selfExcludedUntil):null;
  await query(`UPDATE responsible_play_profiles SET deposit_daily_limit=$1,deposit_weekly_limit=$2,deposit_monthly_limit=$3,spend_daily_limit=$4,session_minutes_limit=$5,cooling_off_until=$6,self_excluded_until=$7,pending_limits=NULL,pending_effective_at=NULL,source='ADMIN',updated_by=$8,updated_at=now() WHERE member_id=$9`,[d,w,m,s,mins,cooling,self,session.userId,memberId]);
  await audit({actorId:session.userId,actorRole:session.roles.join(','),action:'RESPONSIBLE_PLAY_ADMIN_UPDATED',targetType:'USER',targetId:memberId,ip});return getResponsiblePlay(memberId);
}

export async function enforceResponsiblePlay(memberId,{kind,amount,client=null}={}){
  const db=client||{query};await db.query(`INSERT INTO responsible_play_profiles(member_id) VALUES($1) ON CONFLICT(member_id) DO NOTHING`,[memberId]);
  const profile=(await db.query(`SELECT * FROM responsible_play_profiles WHERE member_id=$1`,[memberId])).rows[0];const now=new Date();
  assert(!profile.self_excluded_until||new Date(profile.self_excluded_until)<=now,403,'Akun sedang dalam periode self-exclusion.','SELF_EXCLUDED');
  assert(!profile.cooling_off_until||new Date(profile.cooling_off_until)<=now,403,'Akun sedang dalam periode cooling-off.','COOLING_OFF_ACTIVE');
  if(kind==='DEPOSIT'){
    const totals=(await db.query(`SELECT COALESCE(SUM(amount) FILTER(WHERE created_at>=date_trunc('day',now())),0)::bigint d,COALESCE(SUM(amount) FILTER(WHERE created_at>=date_trunc('week',now())),0)::bigint w,COALESCE(SUM(amount) FILTER(WHERE created_at>=date_trunc('month',now())),0)::bigint m FROM wallet_requests WHERE member_id=$1 AND request_type='DEPOSIT' AND status<>'REJECTED'`,[memberId])).rows[0];
    if(profile.deposit_daily_limit!==null)assert(Number(totals.d)+amount<=Number(profile.deposit_daily_limit),409,'Batas deposit harian telah tercapai.','RESPONSIBLE_DEPOSIT_DAILY_LIMIT');
    if(profile.deposit_weekly_limit!==null)assert(Number(totals.w)+amount<=Number(profile.deposit_weekly_limit),409,'Batas deposit mingguan telah tercapai.','RESPONSIBLE_DEPOSIT_WEEKLY_LIMIT');
    if(profile.deposit_monthly_limit!==null)assert(Number(totals.m)+amount<=Number(profile.deposit_monthly_limit),409,'Batas deposit bulanan telah tercapai.','RESPONSIBLE_DEPOSIT_MONTHLY_LIMIT');
  }
  if(kind==='BET'&&profile.spend_daily_limit!==null){
    const totals=(await db.query(`SELECT (COALESCE((SELECT SUM(total_stake) FROM bet_orders WHERE member_id=$1 AND status NOT IN('DRAFT','CANCELLED','VOID') AND created_at>=date_trunc('day',now())),0)+COALESCE((SELECT SUM(total_stake) FROM sportsbook_tickets WHERE member_id=$1 AND status<>'VOID' AND created_at>=date_trunc('day',now())),0))::bigint total`,[memberId])).rows[0];
    assert(Number(totals.total||0)+amount<=Number(profile.spend_daily_limit),409,'Batas pengeluaran harian telah tercapai.','RESPONSIBLE_SPEND_DAILY_LIMIT');
  }
  return mapResponsible(profile);
}

export async function getPlayer360(session,memberId){
  requirePermission(session,'members:read');const base=await getMemberDetail(session,memberId);const canCompliance=hasPermission(session,'compliance:read'),canRisk=hasPermission(session,'risk:read'),canSecurity=hasPermission(session,'security:read'),canResponsible=hasPermission(session,'responsible:write');
  const compliance=canCompliance?await ensureCompliance(memberId):null;const responsible=canResponsible?await ensureResponsible(memberId):null;
  const [kyc,risk,cases,security,activity]=await Promise.all([
    canCompliance?query(`SELECT id,status,document_type,document_reference,provider_name,provider_reference,review_notes,reviewed_at,created_at FROM kyc_reviews WHERE member_id=$1 ORDER BY created_at DESC LIMIT 20`,[memberId]):Promise.resolve({rows:[]}),
    canRisk?query(`SELECT id,category,severity,score,title,status,evidence,created_at,resolved_at FROM risk_alerts WHERE member_id=$1 ORDER BY created_at DESC LIMIT 30`,[memberId]):Promise.resolve({rows:[]}),
    query(`SELECT id,case_number,category,priority,status,subject,assigned_to,created_at,updated_at FROM support_cases WHERE member_id=$1 ORDER BY created_at DESC LIMIT 30`,[memberId]),
    canSecurity?query(`SELECT event_type,severity,ip_address,details,created_at FROM security_events WHERE member_id=$1 ORDER BY created_at DESC LIMIT 30`,[memberId]):Promise.resolve({rows:[]}),
    query(`SELECT (SELECT COUNT(*)::int FROM bet_orders WHERE member_id=$1) lottery_bets,(SELECT COUNT(*)::int FROM sportsbook_tickets WHERE member_id=$1) sportsbook_bets,(SELECT COUNT(*)::int FROM wallet_requests WHERE member_id=$1 AND request_type='DEPOSIT' AND status='APPROVED') deposits,(SELECT COUNT(*)::int FROM wallet_requests WHERE member_id=$1 AND request_type='WITHDRAW' AND status='APPROVED') withdraws`,[memberId])
  ]);
  return{...base,compliance:mapCompliance(compliance),responsiblePlay:mapResponsible(responsible),kycReviews:kyc.rows,riskAlerts:risk.rows,supportCases:cases.rows,securityEvents:security.rows,activity:activity.rows[0],capabilities:{compliance:canCompliance,risk:canRisk,security:canSecurity,responsible:canResponsible}};
}

export async function listCompliance(session,{status='',limit=300}={}){requirePermission(session,'compliance:read');const values=[];let where='';if(status){values.push(clean(status,20).toUpperCase());where=`WHERE COALESCE(c.kyc_status,'UNVERIFIED')=$1`;}values.push(Math.min(Number(limit)||300,1000));const lp=values.length;const {rows}=await query(`SELECT u.id,u.username,u.email,u.status,COALESCE(c.kyc_status,'UNVERIFIED') kyc_status,COALESCE(c.risk_score,0) risk_score,COALESCE(c.risk_level,'LOW') risk_level,c.verification_provider,c.verification_reference,c.last_reviewed_at FROM users u LEFT JOIN member_compliance_profiles c ON c.member_id=u.id WHERE NOT EXISTS(SELECT 1 FROM user_roles ur WHERE ur.user_id=u.id) ${where?`AND ${where.replace(/^WHERE /,'')}`:''} ORDER BY COALESCE(c.risk_score,0) DESC,u.created_at DESC LIMIT $${lp}`,values);return rows.map(x=>({id:x.id,username:x.username,email:x.email,status:x.status,kycStatus:x.kyc_status,riskScore:x.risk_score,riskLevel:x.risk_level,verificationProvider:x.verification_provider,verificationReference:x.verification_reference,lastReviewedAt:x.last_reviewed_at}));}

export async function reviewKyc(session,memberId,input,ip=''){
  requirePermission(session,'compliance:write');await ensureCompliance(memberId);const status=clean(input.status,20).toUpperCase();assert(['PENDING','VERIFIED','REJECTED','REVIEW'].includes(status),400,'Status KYC tidak valid.','KYC_STATUS_INVALID');const id=randomUUID();
  const documentType=nullable(input.documentType,60),documentReference=nullable(input.documentReference,180),providerName=nullable(input.providerName,80),providerReference=nullable(input.providerReference,180),notes=nullable(input.notes,1500);
  await query(`INSERT INTO kyc_reviews(id,member_id,status,document_type,document_reference,provider_name,provider_reference,review_notes,requested_by,reviewed_by,reviewed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9,now())`,[id,memberId,status,documentType,documentReference,providerName,providerReference,notes,session.userId]);
  await query(`UPDATE member_compliance_profiles SET kyc_status=$1,verification_provider=$2,verification_reference=$3,verified_at=CASE WHEN $1='VERIFIED' THEN now() ELSE verified_at END,last_reviewed_at=now(),reviewed_by=$4,notes=$5,updated_at=now() WHERE member_id=$6`,[status,providerName,providerReference,session.userId,notes,memberId]);
  await audit({actorId:session.userId,actorRole:session.roles.join(','),action:'KYC_REVIEW_COMPLETED',targetType:'USER',targetId:memberId,details:{status,documentType,providerName},ip});return getPlayer360(session,memberId);
}

export async function listSecurityEvents(session,{severity='',limit=300}={}){requirePermission(session,'security:read');const values=[];let clause='';if(severity){values.push(clean(severity,20).toUpperCase());clause=`WHERE e.severity=$1`;}values.push(Math.min(Number(limit)||300,1000));const {rows}=await query(`SELECT e.id,e.channel,e.event_type,e.severity,e.username_hint,e.ip_address,e.details,e.created_at,u.username FROM security_events e LEFT JOIN users u ON u.id=e.member_id ${clause} ORDER BY e.created_at DESC LIMIT $${values.length}`,values);return rows.map(x=>({id:x.id,channel:x.channel,eventType:x.event_type,severity:x.severity,username:x.username||x.username_hint,ipAddress:x.ip_address,details:x.details,createdAt:x.created_at}));}

async function openRiskAlert({memberId=null,category,severity,score,title,description,evidence,fingerprint}){await query(`INSERT INTO risk_alerts(id,member_id,category,severity,score,title,description,fingerprint,evidence) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) ON CONFLICT DO NOTHING`,[randomUUID(),memberId,category,severity,score,title,description,fingerprint,JSON.stringify(evidence||{})]);}

export async function runRiskScan(session,ip=''){
  requirePermission(session,'risk:write');let createdBefore=Number((await query(`SELECT COUNT(*)::int c FROM risk_alerts WHERE status IN('OPEN','IN_REVIEW')`)).rows[0].c);
  const failed=await query(`SELECT member_id,MAX(username_hint) username,COUNT(*)::int attempts,COUNT(DISTINCT ip_address)::int ips FROM security_events WHERE event_type='MEMBER_LOGIN_FAILED' AND created_at>now()-interval '24 hours' AND member_id IS NOT NULL GROUP BY member_id HAVING COUNT(*)>=5`);
  for(const x of failed.rows){const score=Math.min(95,45+x.attempts*4+x.ips*3);await openRiskAlert({memberId:x.member_id,category:'ACCOUNT_TAKEOVER',severity:severityFor(score),score,title:'Repeated failed login',description:'Banyak percobaan login gagal dalam 24 jam.',evidence:{attempts:x.attempts,distinctIps:x.ips},fingerprint:`login-fail:${x.member_id}:${new Date().toISOString().slice(0,10)}`});}
  const velocity=await query(`SELECT member_id,COUNT(*)::int requests,COALESCE(SUM(amount),0)::bigint amount FROM wallet_requests WHERE created_at>now()-interval '1 hour' GROUP BY member_id HAVING COUNT(*)>=5`);
  for(const x of velocity.rows){const score=Math.min(92,50+x.requests*5);await openRiskAlert({memberId:x.member_id,category:'TRANSACTION_VELOCITY',severity:severityFor(score),score,title:'High wallet request velocity',description:'Frekuensi pengajuan wallet tinggi dalam satu jam.',evidence:{requests:x.requests,amount:Number(x.amount)},fingerprint:`wallet-velocity:${x.member_id}:${new Date().toISOString().slice(0,13)}`});}
  const movement=await query(`SELECT member_id,COALESCE(SUM(amount) FILTER(WHERE request_type='DEPOSIT'),0)::bigint deposits,COALESCE(SUM(amount) FILTER(WHERE request_type='WITHDRAW'),0)::bigint withdraws,COUNT(*)::int requests FROM wallet_requests WHERE status='APPROVED' AND reviewed_at>now()-interval '24 hours' GROUP BY member_id HAVING COALESCE(SUM(amount) FILTER(WHERE request_type='DEPOSIT'),0)>=10000000 AND COALESCE(SUM(amount) FILTER(WHERE request_type='WITHDRAW'),0)>=8000000`);
  for(const x of movement.rows){const dep=Number(x.deposits),wd=Number(x.withdraws),ratio=dep?wd/dep:0;if(ratio>=0.8){const score=Math.min(94,65+Math.round(Math.min(ratio,1.5)*15));await openRiskAlert({memberId:x.member_id,category:'TRANSACTION_REVIEW',severity:severityFor(score),score,title:'Rapid deposit/withdraw movement',description:'Deposit dan withdrawal bernilai tinggi terjadi dalam jendela 24 jam dan memerlukan review transaksi.',evidence:{deposits:dep,withdraws:wd,withdrawToDepositRatio:Number(ratio.toFixed(2)),requests:x.requests},fingerprint:`movement:${x.member_id}:${new Date().toISOString().slice(0,10)}`});}}
  const duplicate=await query(`SELECT account_number,COUNT(*)::int members,array_agg(id) ids FROM users WHERE account_number IS NOT NULL AND btrim(account_number)<>'' AND NOT EXISTS(SELECT 1 FROM user_roles ur WHERE ur.user_id=users.id) GROUP BY account_number HAVING COUNT(*)>1`);
  for(const x of duplicate.rows){for(const id of x.ids){const score=Math.min(85,55+x.members*8);await openRiskAlert({memberId:id,category:'SHARED_PAYMENT_ACCOUNT',severity:severityFor(score),score,title:'Shared withdrawal account',description:'Nomor rekening digunakan oleh lebih dari satu member.',evidence:{memberCount:x.members,accountFingerprint:hash(x.account_number).slice(0,16)},fingerprint:`shared-account:${id}:${hash(x.account_number).slice(0,20)}`});}}
  const open=await query(`SELECT member_id,MAX(score)::int score FROM risk_alerts WHERE status IN('OPEN','IN_REVIEW') AND member_id IS NOT NULL GROUP BY member_id`);for(const r of open.rows){await ensureCompliance(r.member_id);await query(`UPDATE member_compliance_profiles SET risk_score=$1,risk_level=$2,updated_at=now() WHERE member_id=$3`,[r.score,severityFor(r.score),r.member_id]);}
  const createdAfter=Number((await query(`SELECT COUNT(*)::int c FROM risk_alerts WHERE status IN('OPEN','IN_REVIEW')`)).rows[0].c);await audit({actorId:session.userId,actorRole:session.roles.join(','),action:'RISK_SCAN_EXECUTED',targetType:'SYSTEM',targetId:'RISK_ENGINE',details:{newAlerts:Math.max(0,createdAfter-createdBefore)},ip});return{newAlerts:Math.max(0,createdAfter-createdBefore),openAlerts:createdAfter,scannedAt:new Date().toISOString()};
}

export async function listRiskAlerts(session,{status='OPEN',limit=300}={}){requirePermission(session,'risk:read');const values=[];let where='';if(status){values.push(clean(status,20).toUpperCase());where=`WHERE r.status=$1`;}values.push(Math.min(Number(limit)||300,1000));const {rows}=await query(`SELECT r.*,u.username FROM risk_alerts r LEFT JOIN users u ON u.id=r.member_id ${where} ORDER BY CASE r.severity WHEN 'CRITICAL' THEN 4 WHEN 'HIGH' THEN 3 WHEN 'MEDIUM' THEN 2 ELSE 1 END DESC,r.created_at DESC LIMIT $${values.length}`,values);return rows.map(x=>({id:x.id,memberId:x.member_id,username:x.username,category:x.category,severity:x.severity,score:x.score,title:x.title,description:x.description,evidence:x.evidence,status:x.status,resolution:x.resolution,createdAt:x.created_at,resolvedAt:x.resolved_at}));}

export async function resolveRiskAlert(session,id,input,ip=''){
  requirePermission(session,'risk:write');const status=clean(input.status,20).toUpperCase();assert(['IN_REVIEW','RESOLVED','DISMISSED'].includes(status),400,'Status risk tidak valid.','RISK_STATUS_INVALID');const resolution=nullable(input.resolution,1500);const {rows}=await query(`UPDATE risk_alerts SET status=$1,resolution=$2,assigned_to=COALESCE(assigned_to,$3),resolved_by=CASE WHEN $1 IN('RESOLVED','DISMISSED') THEN $3 ELSE resolved_by END,resolved_at=CASE WHEN $1 IN('RESOLVED','DISMISSED') THEN now() ELSE resolved_at END,updated_at=now() WHERE id=$4 RETURNING *`,[status,resolution,session.userId,id]);assert(rows[0],404,'Risk alert tidak ditemukan.','RISK_NOT_FOUND');await audit({actorId:session.userId,actorRole:session.roles.join(','),action:'RISK_ALERT_UPDATED',targetType:'RISK_ALERT',targetId:id,details:{status},ip});return rows[0];
}

function caseNumber(){return `A7-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${randomUUID().slice(0,8).toUpperCase()}`;}
export async function createMemberSupportCase(session,input,ip=''){const subject=clean(input.subject,160),description=clean(input.description,3000),category=clean(input.category||'GENERAL',60).toUpperCase();assert(subject.length>=4&&description.length>=10,400,'Subjek dan deskripsi tiket belum lengkap.','CASE_INPUT_INVALID');const id=randomUUID(),number=caseNumber();await query(`INSERT INTO support_cases(id,case_number,member_id,category,priority,status,subject,description,created_by) VALUES($1,$2,$3,$4,'NORMAL','OPEN',$5,$6,$3)`,[id,number,session.userId,category,subject,description]);await audit({actorId:session.userId,actorRole:'MEMBER',action:'SUPPORT_CASE_CREATED',targetType:'SUPPORT_CASE',targetId:id,details:{caseNumber:number,category},ip});return{id,caseNumber:number,status:'OPEN',subject,category,createdAt:new Date().toISOString()};}
export async function listMemberSupportCases(memberId){const {rows}=await query(`SELECT id,case_number,category,priority,status,subject,description,resolution,created_at,updated_at FROM support_cases WHERE member_id=$1 ORDER BY created_at DESC LIMIT 100`,[memberId]);return rows.map(x=>({id:x.id,caseNumber:x.case_number,category:x.category,priority:x.priority,status:x.status,subject:x.subject,description:x.description,resolution:x.resolution,createdAt:x.created_at,updatedAt:x.updated_at}));}
export async function listSupportCases(session,{status='',limit=300}={}){requirePermission(session,'support:write');const values=[];let where='';if(status){values.push(clean(status,30).toUpperCase());where=`WHERE c.status=$1`;}values.push(Math.min(Number(limit)||300,1000));const {rows}=await query(`SELECT c.*,u.username,a.username assigned_username FROM support_cases c JOIN users u ON u.id=c.member_id LEFT JOIN users a ON a.id=c.assigned_to ${where} ORDER BY CASE c.priority WHEN 'URGENT' THEN 4 WHEN 'HIGH' THEN 3 WHEN 'NORMAL' THEN 2 ELSE 1 END DESC,c.created_at DESC LIMIT $${values.length}`,values);return rows.map(x=>({id:x.id,caseNumber:x.case_number,memberId:x.member_id,username:x.username,category:x.category,priority:x.priority,status:x.status,subject:x.subject,description:x.description,assignedTo:x.assigned_username,resolution:x.resolution,createdAt:x.created_at,updatedAt:x.updated_at}));}
export async function updateSupportCase(session,id,input,ip=''){requirePermission(session,'support:write');const status=clean(input.status,30).toUpperCase();assert(['OPEN','ASSIGNED','WAITING_MEMBER','RESOLVED','CLOSED'].includes(status),400,'Status case tidak valid.','CASE_STATUS_INVALID');const priority=clean(input.priority||'NORMAL',20).toUpperCase();assert(['LOW','NORMAL','HIGH','URGENT'].includes(priority),400,'Priority tidak valid.','CASE_PRIORITY_INVALID');const resolution=nullable(input.resolution,2000);const {rows}=await query(`UPDATE support_cases SET status=$1,priority=$2,assigned_to=CASE WHEN $1 IN('ASSIGNED','WAITING_MEMBER') THEN COALESCE(assigned_to,$3) ELSE assigned_to END,resolution=$4,resolved_by=CASE WHEN $1 IN('RESOLVED','CLOSED') THEN $3 ELSE resolved_by END,resolved_at=CASE WHEN $1 IN('RESOLVED','CLOSED') THEN now() ELSE resolved_at END,updated_at=now() WHERE id=$5 RETURNING *`,[status,priority,session.userId,resolution,id]);assert(rows[0],404,'Support case tidak ditemukan.','CASE_NOT_FOUND');await audit({actorId:session.userId,actorRole:session.roles.join(','),action:'SUPPORT_CASE_UPDATED',targetType:'SUPPORT_CASE',targetId:id,details:{status,priority},ip});return rows[0];}

export async function createReconciliation(session,input,ip=''){
  requirePermission(session,'reconciliation:write');const date=clean(input.businessDate,10);assert(/^\d{4}-\d{2}-\d{2}$/.test(date),400,'Business date tidak valid.','RECON_DATE_INVALID');const type=clean(input.requestType,20).toUpperCase();assert(['DEPOSIT','WITHDRAW'].includes(type),400,'Jenis reconciliation tidak valid.','RECON_TYPE_INVALID');const external=bounded(input.externalAmount,0,9000000000000,'external amount')??0;const method=nullable(input.paymentMethodId,60);
  const values=[date,type];let methodClause='';if(method){values.push(method);methodClause=` AND payment_method_id=$${values.length}`;}
  const r=(await query(`SELECT COUNT(*)::int c,COALESCE(SUM(amount),0)::bigint total FROM wallet_requests WHERE request_type=$2 AND status='APPROVED' AND COALESCE(settled_at,reviewed_at)::date=$1::date${methodClause}`,values)).rows[0];const system=Number(r.total||0),diff=external-system,status=diff===0?'MATCHED':'MISMATCH',id=randomUUID();
  await query(`INSERT INTO reconciliation_runs(id,business_date,request_type,payment_method_id,system_amount,external_amount,difference_amount,transaction_count,status,reference_note,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,date,type,method,system,external,diff,r.c,status,nullable(input.referenceNote,500),session.userId]);await audit({actorId:session.userId,actorRole:session.roles.join(','),action:'RECONCILIATION_RUN_CREATED',targetType:'RECONCILIATION',targetId:id,details:{date,type,system,external,diff,status},ip});return{id,businessDate:date,requestType:type,systemAmount:system,externalAmount:external,differenceAmount:diff,transactionCount:r.c,status};
}
export async function listReconciliations(session,{limit=200}={}){requirePermission(session,'reconciliation:write');const {rows}=await query(`SELECT r.*,p.name payment_name,u.username created_username FROM reconciliation_runs r LEFT JOIN payment_methods p ON p.id=r.payment_method_id LEFT JOIN users u ON u.id=r.created_by ORDER BY r.business_date DESC,r.created_at DESC LIMIT $1`,[Math.min(Number(limit)||200,1000)]);return rows.map(x=>({id:x.id,businessDate:x.business_date,requestType:x.request_type,paymentMethod:x.payment_name,systemAmount:Number(x.system_amount),externalAmount:Number(x.external_amount),differenceAmount:Number(x.difference_amount),transactionCount:x.transaction_count,status:x.status,referenceNote:x.reference_note,createdBy:x.created_username,createdAt:x.created_at}));}

export async function reportCenter(session,{days=30}={}){requirePermission(session,'reports:read');const d=Math.min(Math.max(Number(days)||30,1),90);const [daily,members,risk,support]=await Promise.all([
  query(`WITH dates AS (SELECT generate_series(current_date-($1::int-1),current_date,'1 day')::date d) SELECT dates.d,COALESCE(SUM(w.amount) FILTER(WHERE w.request_type='DEPOSIT' AND w.status='APPROVED'),0)::bigint deposits,COALESCE(SUM(w.amount) FILTER(WHERE w.request_type='WITHDRAW' AND w.status='APPROVED'),0)::bigint withdraws,COUNT(w.id) FILTER(WHERE w.status IN('PENDING','AWAITING_SECOND_APPROVAL','PROCESSING'))::int pending FROM dates LEFT JOIN wallet_requests w ON w.created_at::date=dates.d GROUP BY dates.d ORDER BY dates.d`,[d]),
  query(`SELECT COUNT(*) FILTER(WHERE NOT EXISTS(SELECT 1 FROM user_roles ur WHERE ur.user_id=users.id))::int total,COUNT(*) FILTER(WHERE status='ACTIVE' AND NOT EXISTS(SELECT 1 FROM user_roles ur WHERE ur.user_id=users.id))::int active,COUNT(*) FILTER(WHERE created_at>=current_date AND NOT EXISTS(SELECT 1 FROM user_roles ur WHERE ur.user_id=users.id))::int new_today FROM users`),
  query(`SELECT COUNT(*) FILTER(WHERE status IN('OPEN','IN_REVIEW'))::int open,COUNT(*) FILTER(WHERE severity IN('HIGH','CRITICAL') AND status IN('OPEN','IN_REVIEW'))::int high FROM risk_alerts`),
  query(`SELECT COUNT(*) FILTER(WHERE status NOT IN('RESOLVED','CLOSED'))::int open,COUNT(*) FILTER(WHERE priority='URGENT' AND status NOT IN('RESOLVED','CLOSED'))::int urgent FROM support_cases`)
  ]);
  const betting=await query(`SELECT COALESCE((SELECT SUM(total_stake) FROM bet_orders WHERE created_at>=current_date-$1::int),0)::bigint lottery_stake,COALESCE((SELECT SUM(total_stake) FROM sportsbook_tickets WHERE created_at>=current_date-$1::int),0)::bigint sportsbook_stake`,[d]);
  return{days:d,members:members.rows[0],risk:risk.rows[0],support:support.rows[0],betting:{lotteryStake:Number(betting.rows[0].lottery_stake),sportsbookStake:Number(betting.rows[0].sportsbook_stake)},daily:daily.rows.map(x=>({date:x.d,deposits:Number(x.deposits),withdraws:Number(x.withdraws),pending:x.pending}))};
}

export async function operationsSummary(session){requirePermission(session,'members:read');const {rows}=await query(`SELECT (SELECT COUNT(*)::int FROM member_compliance_profiles WHERE kyc_status IN('PENDING','REVIEW')) kyc_queue,(SELECT COUNT(*)::int FROM risk_alerts WHERE status IN('OPEN','IN_REVIEW')) risk_open,(SELECT COUNT(*)::int FROM risk_alerts WHERE severity IN('HIGH','CRITICAL') AND status IN('OPEN','IN_REVIEW')) risk_high,(SELECT COUNT(*)::int FROM support_cases WHERE status NOT IN('RESOLVED','CLOSED')) support_open,(SELECT COUNT(*)::int FROM reconciliation_runs WHERE status='MISMATCH' AND created_at>now()-interval '7 days') reconciliation_mismatch,(SELECT COUNT(*)::int FROM security_events WHERE severity IN('HIGH','CRITICAL') AND created_at>now()-interval '24 hours') security_high_24h`);const r=rows[0];return{kycQueue:r.kyc_queue,riskOpen:r.risk_open,riskHigh:r.risk_high,supportOpen:r.support_open,reconciliationMismatch:r.reconciliation_mismatch,securityHigh24h:r.security_high_24h};}
